repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # latest stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.9.1  # latest stable version
    hooks:
      - id: black
